name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
          output-directory: 'out'
      - name: Compile References
        uses: actions/latex-biber-action@v2
        with:
          filename: 'cv'
          output-directory: 'out'
      - name: ReCompile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
          output-directory: 'out'
